FROM ubuntu:18.04
MAINTAINER Leonardo Edgar

ARG USER
ARG GROUP
ARG UID
ARG GID

# Install core linux tools
RUN apt-get update && apt-get install -y --no-install-recommends \
	apt-utils lsb-release sudo unzip wget ssh vim curl ca-certificates gnupg\
	&& rm -rf /var/lib/apt/lists/*

# Install npm and nodejs
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
	&& apt-get install -y nodejs --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

# User and permissions
ARG HOME=/home/${USER}
RUN mkdir -p /etc/sudoers.d \
    && groupadd -g ${GID} ${GROUP} \
    && useradd -d ${HOME} -u ${UID} -g ${GID} -m -s /bin/bash ${USER} \
    && echo "${USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/sudoers_${USER}
USER ${USER}
RUN sudo usermod -a -G video ${USER}

WORKDIR ${HOME}

# Install node modules
COPY --chown=${USER} wacu-wacu-server/package.json			wacu-wacu-server/package.json
RUN cd wacu-wacu-server && npm install
COPY --chown=${USER} wacu-wacu-client/package.json			wacu-wacu-client/package.json
RUN cd wacu-wacu-client && npm install
COPY --chown=${USER} wacu-wacu-manager/package.json			wacu-wacu-manager/package.json
RUN cd wacu-wacu-manager && npm install
